name: Build RPM

on:
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.29.2"

jobs:
  build_rpm:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake libgtk-3-dev ninja-build libayatana-appindicator3-dev libfuse2 libmpv-dev mpv libmimalloc-dev libmimalloc2.0 rpm libtag1-dev

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"

      - name: Enable Linux Desktop
        run: flutter config --enable-linux-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Enable flutter_distributor
        run: dart pub global activate flutter_distributor

      - name: Build RPM
        run: PATH="$PATH:$HOME/.pub-cache/bin" flutter_distributor package --platform linux --targets rpm

      - name: Upload RPM
        uses: actions/upload-artifact@v4
        with:
         name: result-rpm
         path: dist/*
