name: Build TAR on ARM

on:
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.29.2"

jobs:
  build_tar_arm:
    runs-on: [self-hosted, linux, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake libgtk-3-dev ninja-build libayatana-appindicator3-dev libfuse2 libmpv-dev mpv libmimalloc-dev libmimalloc2.0

      - name: Enable Linux Desktop
        run: flutter config --enable-linux-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Build App
        run: |
          flutter build linux


      - name: Create TAR
        run: |
          cd build/linux/arm64/release/bundle
          tar -czvf../../../../../photos-linux.tar.gz *
          cd ../../../../..

      - name: Upload TAR as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: result-tar
          path: photos-linux.tar.gz