name: Build RPM on ARM

on:
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.29.2"

jobs:
  build_rpm_arm:
    runs-on: [self-hosted, linux, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake libgtk-3-dev ninja-build libayatana-appindicator3-dev libfuse2 libmpv-dev mpv libmimalloc-dev libmimalloc2.0 rpm

      - name: Enable Linux Desktop
        run: flutter config --enable-linux-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Enable flutter_distributor
        run: dart pub global activate flutter_distributor

      - name: Build RPM
        run: PATH="$PATH:$HOME/.pub-cache/bin" flutter_distributor package --platform linux --targets rpm

      - name: Upload RPM
        uses: actions/upload-artifact@v4
        with:
          name: result-rpm-arm
          path: dist/*